name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install geos
      run: |
        sudo apt-get update
        sudo apt-get install -y libgeos-dev
    - name: Install
      run: |
        pip install pytest
        pip install .
    - name: Test with pytest
      run: pytest
